#This is test workflow created to create s3 bkt
name: Manual work flow created - S3 bkt create
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  creates3_bucket:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v4

      - name: Set Up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: ${{ secrets.AWS_REGION}}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: List s3 Buckets
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "Listing S3 Buckets"
          aws s3 ls


